apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber"
        dapr.io/app-port: "8081"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: subscriber
        image: subscriber:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
spec:
  selector:
    app: subscriber
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP 